/**
 * ProcessMaker API
 * This ProcessMaker Core API provide access to the new generation engine with BPMN 2.0 support. The current Alpha 1.0 version supports  the part of BPM system functionality like process import, process execution, task assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alpha-program@processmaker.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * TaskInstanceAttributes
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-14T14:31:37.499+02:00")
public class TaskInstanceAttributes   {
  @SerializedName("task_id")
  private String taskId = null;

  @SerializedName("instance_id")
  private String instanceId = null;

  @SerializedName("group_id")
  private String groupId = null;

  @SerializedName("user_id")
  private String userId = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("INITIAL")
    INITIAL("INITIAL"),
    
    @SerializedName("DELEGATED")
    DELEGATED("DELEGATED"),
    
    @SerializedName("STARTED")
    STARTED("STARTED"),
    
    @SerializedName("CANCELLED")
    CANCELLED("CANCELLED"),
    
    @SerializedName("FINISHED")
    FINISHED("FINISHED"),
    
    @SerializedName("COMPLETE")
    COMPLETE("COMPLETE"),
    
    @SerializedName("PAUSED")
    PAUSED("PAUSED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = StatusEnum.INITIAL;

  /**
   * Gets or Sets priority
   */
  public enum PriorityEnum {
    @SerializedName("1")
    _1("1"),
    
    @SerializedName("2")
    _2("2"),
    
    @SerializedName("3")
    _3("3"),
    
    @SerializedName("4")
    _4("4"),
    
    @SerializedName("5")
    _5("5");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("priority")
  private PriorityEnum priority = PriorityEnum._3;

  @SerializedName("delegate_date")
  private DateTime delegateDate = null;

  @SerializedName("start_date")
  private DateTime startDate = null;

  @SerializedName("finish_date")
  private DateTime finishDate = null;

  @SerializedName("task_due_date")
  private DateTime taskDueDate = null;

  @SerializedName("risk_date")
  private DateTime riskDate = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("instance_overdue_percentage")
  private Double instanceOverduePercentage = null;

  @SerializedName("data")
  private String data = null;

  @SerializedName("content")
  private String content = null;

  @SerializedName("created_at")
  private DateTime createdAt = null;

  @SerializedName("updated_at")
  private DateTime updatedAt = null;

  public TaskInstanceAttributes taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b11", required = true, value = "")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public TaskInstanceAttributes instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b11", required = true, value = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  public TaskInstanceAttributes groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b11", value = "")
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public TaskInstanceAttributes userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b11", value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public TaskInstanceAttributes status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public TaskInstanceAttributes priority(PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public PriorityEnum getPriority() {
    return priority;
  }

  public void setPriority(PriorityEnum priority) {
    this.priority = priority;
  }

  public TaskInstanceAttributes delegateDate(DateTime delegateDate) {
    this.delegateDate = delegateDate;
    return this;
  }

   /**
   * Get delegateDate
   * @return delegateDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDelegateDate() {
    return delegateDate;
  }

  public void setDelegateDate(DateTime delegateDate) {
    this.delegateDate = delegateDate;
  }

  public TaskInstanceAttributes startDate(DateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(DateTime startDate) {
    this.startDate = startDate;
  }

  public TaskInstanceAttributes finishDate(DateTime finishDate) {
    this.finishDate = finishDate;
    return this;
  }

   /**
   * Get finishDate
   * @return finishDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getFinishDate() {
    return finishDate;
  }

  public void setFinishDate(DateTime finishDate) {
    this.finishDate = finishDate;
  }

  public TaskInstanceAttributes taskDueDate(DateTime taskDueDate) {
    this.taskDueDate = taskDueDate;
    return this;
  }

   /**
   * Get taskDueDate
   * @return taskDueDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getTaskDueDate() {
    return taskDueDate;
  }

  public void setTaskDueDate(DateTime taskDueDate) {
    this.taskDueDate = taskDueDate;
  }

  public TaskInstanceAttributes riskDate(DateTime riskDate) {
    this.riskDate = riskDate;
    return this;
  }

   /**
   * Get riskDate
   * @return riskDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getRiskDate() {
    return riskDate;
  }

  public void setRiskDate(DateTime riskDate) {
    this.riskDate = riskDate;
  }

  public TaskInstanceAttributes duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public TaskInstanceAttributes instanceOverduePercentage(Double instanceOverduePercentage) {
    this.instanceOverduePercentage = instanceOverduePercentage;
    return this;
  }

   /**
   * Get instanceOverduePercentage
   * @return instanceOverduePercentage
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getInstanceOverduePercentage() {
    return instanceOverduePercentage;
  }

  public void setInstanceOverduePercentage(Double instanceOverduePercentage) {
    this.instanceOverduePercentage = instanceOverduePercentage;
  }

  public TaskInstanceAttributes data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public TaskInstanceAttributes content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public TaskInstanceAttributes createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public TaskInstanceAttributes updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskInstanceAttributes taskInstanceAttributes = (TaskInstanceAttributes) o;
    return Objects.equals(this.taskId, taskInstanceAttributes.taskId) &&
        Objects.equals(this.instanceId, taskInstanceAttributes.instanceId) &&
        Objects.equals(this.groupId, taskInstanceAttributes.groupId) &&
        Objects.equals(this.userId, taskInstanceAttributes.userId) &&
        Objects.equals(this.status, taskInstanceAttributes.status) &&
        Objects.equals(this.priority, taskInstanceAttributes.priority) &&
        Objects.equals(this.delegateDate, taskInstanceAttributes.delegateDate) &&
        Objects.equals(this.startDate, taskInstanceAttributes.startDate) &&
        Objects.equals(this.finishDate, taskInstanceAttributes.finishDate) &&
        Objects.equals(this.taskDueDate, taskInstanceAttributes.taskDueDate) &&
        Objects.equals(this.riskDate, taskInstanceAttributes.riskDate) &&
        Objects.equals(this.duration, taskInstanceAttributes.duration) &&
        Objects.equals(this.instanceOverduePercentage, taskInstanceAttributes.instanceOverduePercentage) &&
        Objects.equals(this.data, taskInstanceAttributes.data) &&
        Objects.equals(this.content, taskInstanceAttributes.content) &&
        Objects.equals(this.createdAt, taskInstanceAttributes.createdAt) &&
        Objects.equals(this.updatedAt, taskInstanceAttributes.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskId, instanceId, groupId, userId, status, priority, delegateDate, startDate, finishDate, taskDueDate, riskDate, duration, instanceOverduePercentage, data, content, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskInstanceAttributes {\n");
    
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    delegateDate: ").append(toIndentedString(delegateDate)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    finishDate: ").append(toIndentedString(finishDate)).append("\n");
    sb.append("    taskDueDate: ").append(toIndentedString(taskDueDate)).append("\n");
    sb.append("    riskDate: ").append(toIndentedString(riskDate)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    instanceOverduePercentage: ").append(toIndentedString(instanceOverduePercentage)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

